- name: Configure and deploy Docker container
  hosts: all
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install Git
      yum:
        name: git
        state: present

    - name: Clone the repository
      git:
        repo: "https://github.com/magnuslopes23/expenseTracker.git"
        dest: /home/ec2-user/expense-tracker
        version: main

    - name: Build the Docker image
      command: docker build -t expense_tracker /home/ec2-user/expense-tracker
      args:
        chdir: /home/ec2-user/expense-tracker

    - name: Run the Docker container
      command: docker run -d --name expense_tracker_container -p 80:5000 expense_tracker
      ignore_errors: yes

    - name: Ensure Docker container restarts on reboot
      command: docker update --restart always expense_tracker_container
