- name: Configure and deploy Docker containers
  hosts: all
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install Git
      yum:
        name: git
        state: present

    - name: Clone the repository
      git:
        repo: "https://github.com/magnuslopes23/expenseTracker.git"
        dest: /home/ec2-user/expense-tracker
        version: main

    - name: Build and start Docker containers using Docker Compose
      command: docker-compose up -d
      args:
        chdir: /home/ec2-user/expense-tracker

    # - name: Ensure Docker containers restart on reboot
    #   command: docker update --restart always expense_tracker_backend_1 expense_tracker_frontend_1
