name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Docker Images
      - name: Build and tag Docker images
        run: |
          docker build -t expense-tracker-backend ./backend
          docker build -t expense-tracker-frontend ./frontend

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Push images to Docker Hub
      - name: Push images
        run: |
          docker tag expense-tracker-backend ${{ secrets.DOCKER_USERNAME }}/expense-tracker-backend:latest
          docker tag expense-tracker-frontend ${{ secrets.DOCKER_USERNAME }}/expense-tracker-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/expense-tracker-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/expense-tracker-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: SSH into EC2 instance
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd expense-tracker/
            docker pull ${{ secrets.DOCKER_USERNAME }}/expense-tracker-backend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/expense-tracker-frontend:latest
            sudo docker-compose up -d
